### ISSUE TITLE
Variable naming and use.

### ISSUE THREAD

**Issue by SimonGoring** [throughput-ec/UnacquiredSites#9]
In the `nlp_sentence_loader` a variable is defined as `nlp_sentneces` not `sentences`, and then isn't used.  The same variable is defined three times starting on line 37.  Is this used anymore?

https://github.com/throughput-ec/UnacquiredSites/blob/master/src/modules/preprocessing/nlp_sentence_loader.py#L37

**Comment by sedv8808** [comment]
removed this part of file since it is not used.
